[package]
name = "voyage_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
avian3d = { git = "https://github.com/Jondolf/avian", version = "0.1.2" }
bevy_mod_picking = "0.19.1"
bevy_kira_audio = { version = "0.20.0", features = ["mp3"] }
noise = "0.8.2"
transvoxel = "1.0.0"
num-traits = "0.2.14"
num-integer = "0.1.45"
acacia = "0.2.0"
chrono = "0.4.38"
bevy_infinite_grid = { git = "https://github.com/tychedelia/bevy_infinite_grid.git" }
bevy_turborand = "0.9.0"
avian_interpolation3d = { git = "https://github.com/janhohenheim/avian_interpolation", version = "0.1.0" }
avian_pickup = { git = "https://github.com/janhohenheim/avian_pickup", version = "0.1.0" }
bevy_blur_regions = "0.4.0"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[features]
use-debug-plugin = []
