[package]
name = "voyage_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
bevy_xpbd_3d = "0.3"
bevy_mod_picking = "0.17.0"
bevy_kira_audio = "0.18.0"
bevy_flycam = { git = "https://github.com/sburris0/bevy_flycam" }
noise = "0.8.2"
transvoxel = "1.0.0"
num-traits = "0.2.14"
num-integer = "0.1.45"
acacia = "0.2.0"
bevy_oxr = "0.1.0"
color-eyre = "0.6.2"
bevy_infinite_grid = "0.12.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
